apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ELASTIC_URL:   "{{ .Values.elasticsearch.url }}"
  ELASTIC_INDEX: "{{ .Values.elasticsearch.index }}"
  METRICS_PORT:  "{{ .Values.metrics.port }}"
  PCAP_PATH:     "{{ .Values.pcap.path }}"
