apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: pcap-analyzer
spec:
  selector:
    app: pcap-analyzer
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
